[package]
name = 'pallet-stream'
description = 'Manage Stream Entries.'
version = '0.8.0'
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39" }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
cord-primitives = { package = "cord-primitives", path="../../primitives", default-features = false }
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }
pallet-registry = {  default-features = false, path = '../registry' }
serde = { version = "1.0.136", optional = true }

# Substrate dependencies
frame-support = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39", default-features = false }
sp-keystore = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39", default-features = false, optional = true}
frame-benchmarking = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.39", default-features = false, optional = true}


[features]
default = [ 'std' ]
mock = [
  "serde",
  "sp-keystore" 
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "cord-primitives/std",
  "cord-utilities/std",
  "sp-std/std",
  "pallet-registry/std", 
]