[package]
name = 'pallet-chain-space'
description = 'Manage Chain Spaces'
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0" }

[dev-dependencies]
# env_logger = {version = "0.9.0"}
sp-core = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", features = [
	"std",
] }
sp-keystore = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", features = [
	"std",
] }
pallet-balances = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", features = [
	"std",
] }
cord-utilities = { package = "cord-utilities", path = "../../utilities", features = [
	"mock",
] }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.10.0", default-features = false, features = [
	"derive",
] }
bitflags = { version = "1.3.2", default-features = false }
log = { version = "0.4.17", default-features = false }

# Internal dependencies
cord-primitives = { package = "cord-primitives", path = "../../primitives/cord", default-features = false }
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }
identifier = { package = "cord-identifier", path = "../../primitives/identifier", default-features = false }

# Substrate dependencies
frame-benchmarking = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false, optional = true }
frame-support = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false }
sp-core = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false, optional = true }
sp-io = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false, optional = true }
sp-keystore = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false, optional = true }
sp-runtime = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.8.0", default-features = false }


[features]
default = ['std']
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"cord-utilities/runtime-benchmarks",
]
std = [
	"codec/std",
	"identifier/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"cord-primitives/std",
	"cord-utilities/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = ["frame-support/try-runtime", "frame-system/try-runtime"]
