[package]
name = 'cord-primitives'
version = '0.7.0'
authors = ['Dhiway <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[dependencies]
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true }
base58 = "0.2.0"
sp-cid = "0.3.0"
semver = { version = "1.0", default-features = false }
blake2-rfc = {version = "0.2.18", default-features = false}


sp-core = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
frame-system = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
frame-support = { git = "https://github.com/paritytech/substrate",  default-features = false, branch = "polkadot-v0.9.20"}
sp-runtime = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
sp-std = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
sp-api = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
sp-application-crypto = {git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20"}
sp-consensus-aura = {default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20"}

[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "sp-api/std",
  "frame-system/std",
  "frame-support/std",
 	"sp-application-crypto/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-consensus-aura/std",
]