[package]
name = "pallet-did-runtime-api"
description = "Runtime APIs for dealing with DIDs."
version = "0.9.0"
authors = ['Dhiway <info@dhiway.com>', 'BOTLabs GmbH']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.10.0", default-features = false, features = [
	"derive",
] }

# Internal dependencies
pallet-did = { default-features = false, path = '../../pallets/did' }

# Substrate
sp-api = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.3.0", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.3.0", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.3.0" }

[features]
default = ["std"]
std = [
	"frame-system/std",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"scale-info/std",
	"pallet-did/std",
]
