[profile.release]
panic = 'unwind'

[workspace]
members = [
	"primitives",
	"runtime",
	"rpc",
	"executor",
	"inspect",
	"node",
	"pallets/registrar",
	"pallets/schema",
	"pallets/stream",
	"pallets/network-treasury",
	"pallets/nix",
]

