version: '3.8'
services:
  bootnode:
    image: dhiway/cord
    container_name: alice
    networks:
      - cord_network
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9615:9615"
    volumes:
      - /tmp/cord-data:/data
    command: --base-path /data/alice --validator --chain local --alice --port 30333 --rpc-port 9944 --prometheus-port 9615 --prometheus-external --node-key abe47f4e1065d4aa6fb0c1dd69a9a6b63c4551da63aad5f688976f77bd21622f --rpc-methods=Safe --rpc-cors all --telemetry-url "wss://telemetry.cord.network/submit/ 0"
    restart: unless-stopped

  bob_node:
    image: dhiway/cord
    container_name: bob
    networks:
      - cord_network
    ports:
      - "30334:30334"
      - "9934:9934"
      - "9616:9616"
    volumes:
      - /tmp/cord-data:/data
    command: --base-path /data/bob --validator --chain local --bob --port 30334 --rpc-port 9934 --prometheus-port 9616 --prometheus-external --node-key 7609333b3e2e2e0c1b4064f074a7396b53d213e08d356d1be2d48fab3a6cd25a --rpc-methods=Safe --rpc-cors all --telemetry-url "wss://telemetry.cord.network/submit/ 0" --bootnodes /dns4/bootnode/tcp/30333/p2p/12D3KooWSNT7EqipGHpsAYptQfPNrMXdJcgjMd25hnQWwyvHxYnz
    restart: unless-stopped

  charlie_node:
    image: dhiway/cord
    container_name: charlie
    networks:
      - cord_network
    ports:
      - "30335:30335"
      - "9935:9935"
      - "9617:9617"
    volumes:
      - /tmp/cord-data:/data
    command: --base-path /data/charlie --validator --chain local --charlie --port 30335 --rpc-port 9935 --prometheus-port 9617 --prometheus-external --node-key e18d2c105ad8188830979b7bf4e7779361beb9010b6574e1b35a0a354ce02e96 --rpc-methods=Safe --rpc-cors all --telemetry-url "wss://telemetry.cord.network/submit/ 0" --bootnodes /dns4/bootnode/tcp/30333/p2p/12D3KooWSNT7EqipGHpsAYptQfPNrMXdJcgjMd25hnQWwyvHxYnz
    restart: unless-stopped

  dave_node:
    image: dhiway/cord
    container_name: dave
    networks:
      - cord_network
    ports:
      - "30336:30336"
      - "9936:9936"
      - "9618:9618"
    volumes:
      - /tmp/cord-data:/data
    command: --base-path /data/dave --chain local --dave --port 30336 --rpc-port 9936 --prometheus-port 9618 --prometheus-external --node-key f21d3114273b5d6184f9e595dba1850eb64b1e4965cfd2c6130354c67f632f5d --rpc-methods=Safe --rpc-cors all --telemetry-url "wss://telemetry.cord.network/submit/ 0" --bootnodes /dns4/bootnode/tcp/30333/p2p/12D3KooWSNT7EqipGHpsAYptQfPNrMXdJcgjMd25hnQWwyvHxYnz
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - cord_network
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - cord_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    networks:
      - cord_network
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /tmp/cord-data:/host:ro,rslave

networks:
  cord_network:
    driver: bridge

x-lifecycle-hooks:
  before-up:
    - if [ -d /tmp/cord-data ]; then rm -rf /tmp/cord-data; fi
    - mkdir /tmp/cord-data && chmod 777 /tmp/cord-data && chown $USER /tmp/cord-data
 