[package]
name = 'cord-rpc'
version = '0.5.8'
authors = ['Dhiway <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "18.0.0"
cord-primitives = { package = "cord-primitives", path="../primitives"}
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.14" }


