[package]
name = 'pallet-did'
description = "Enables adding and removing decentralized identifiers (DIDs)."
authors = ['Dhiway <info@dhiway.com>', 'BOTLabs GmbH']
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
pallet-balances = { features = ["std"], workspace = true }
frame-benchmarking = { features = ["std"], workspace = true }
sp-keystore = { features = ["std"], workspace = true }


[dependencies]
# External dependencies
log = { workspace = true }
fluent-uri = { workspace = true }

# Internal dependencies
cord-utilities = { workspace = true }
identifier = { workspace = true }
pallet-chain-space = { workspace = true }

# Substrate dependencies
codec = { features = ["derive", "max-encoded-len"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Benchmarking dependencies
frame-benchmarking = { optional = true, workspace = true }
pallet-balances = { optional = true, workspace = true }
sp-keystore = { optional = true, workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"cord-utilities/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"codec/std",
	"pallet-chain-space/std",
	"identifier/std",
	"frame-support/std",
	"frame-system/std",
	"cord-utilities/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"cord-utilities/try-runtime",
]
