[package]
name = 'cord-runtime'
version = '0.7.10'
authors = ['Dhiway Networks <info@dhiway.com>']
build = 'build.rs'
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive","max-encoded-len"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false  }
static_assertions = "1.1.0"

# primitives
cord-primitives = { package = "cord-primitives", path = "../primitives", default-features = false }
cord-runtime-constants = { package = "cord-runtime-constants", path = "./constants", default-features = false }

sp-authority-discovery = {  git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-consensus-babe = {  git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-api = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-inherents = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-offchain = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-std = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-runtime = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-staking = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-core = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
# sp-io = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-session = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-version = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
sp-transaction-pool = {  git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
sp-block-builder = {  git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }

pallet-authority-discovery = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-authorship = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-babe = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
pallet-balances = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-transaction-payment = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
pallet-collective = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-democracy = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-elections-phragmen = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
frame-executive = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-grandpa = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-identity = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-im-online = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-indices = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-membership = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-multisig = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-offences = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-preimage = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-proxy = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-recovery = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
pallet-scheduler = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-session = {git = "https://github.com/dhiway/substrate", features = ["historical"], default-features = false, branch = "release-v0.9.30"}
pallet-sudo = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
frame-support = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-staking = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
frame-system = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
frame-system-rpc-runtime-api = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-timestamp = {git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30"}
pallet-treasury = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }
pallet-utility = { git = "https://github.com/dhiway/substrate", default-features = false, branch = "release-v0.9.30" }

frame-benchmarking = { git = "https://github.com/dhiway/substrate",  default-features = false, optional = true, branch = "release-v0.9.30" }
frame-system-benchmarking = { git = "https://github.com/dhiway/substrate",  default-features = false, optional = true, branch = "release-v0.9.30" }
frame-try-runtime = { git = "https://github.com/dhiway/substrate", default-features = false, optional = true, branch = "release-v0.9.30" }

pallet-schema = {  default-features = false, path = '../pallets/schema' }
pallet-credit-treasury = {  default-features = false, path = '../pallets/credit-treasury' }
pallet-author-registry = {  default-features = false, path = '../pallets/author-registry' }

[dev-dependencies]
hex-literal = "0.3.4"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
keyring = { package = "sp-keyring", git = "https://github.com/dhiway/substrate", branch = "release-v0.9.30" }
separator = "0.4.1"
serde_json = "1.0.81"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.30" }

[features]
default = ['std']
std = [
	"sp-authority-discovery/std",
    "cord-primitives/std",
    'codec/std',
	"scale-info/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-api/std",
	"sp-transaction-pool/std",
	"sp-block-builder/std",
	"sp-offchain/std",
	"sp-std/std",
	"frame-support/std",
	"frame-executive/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-democracy/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-offences/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-sudo/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"pallet-babe/std",
	"pallet-schema/std",
	"pallet-credit-treasury/std",
	"pallet-author-registry/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"sp-version/std",
	"log/std",
	"sp-consensus-babe/std",
	"sp-session/std",
	"cord-runtime-constants/std",
]

runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-recovery/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
]

try-runtime = [
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-babe/try-runtime",
]

# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]
