[package]
name = 'pallet-runtime-upgrade'
description = 'Manage Forkless Runtime Upgrades'
version = "0.8.1"
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.43" }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = [
	"derive",
] }

# Substrate dependencies
frame-system = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.43", default-features = false }
frame-support = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.43", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.43", default-features = false }
sp-io = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.43", default-features = false, optional = true }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-std/std',
	'sp-io/std',
	'scale-info/std',
]
try-runtime = ["frame-support/try-runtime"]
