[package]
name = "pallet-membership"
description = "FRAME membership management pallet - modified to support CORD governance."
authors = [
	"Parity Technologies <admin@parity.io>",
	"Dhiway Networks <info@dhiway.com>",
]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
pallet-network-membership = { workspace = true }

# Substrate dependencies
frame-benchmarking = { optional = true, workspace = true }
frame-system = { workspace = true }
frame-support = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-network-membership/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-network-membership/runtime-benchmarks"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-network-membership/try-runtime",
	"sp-runtime/try-runtime"
]
