[package]
name = 'pallet-mtype'
version = '0.7.2'
edition = '2021'
authors = ['Dhiway <info@dhiway.com>']
description = 'Enables adding #MARK TYPEs (Schemas).'

[[package.metadata.docs.rs]]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
cord-primitives = { package = "cord-primitives", path="../../primitives", default-features = false }

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", default-features = false }

[features]
default = [ 'std' ]
runtime-benchmarks = []
std = [
	'codec/std',
  	"scale-info/std",
  	"cord-primitives/std",
	'frame-support/std',
	'frame-system/std',
	'sp-runtime/std',
	'sp-std/std',
]

