[package]
name = 'pallet-did-name'
description = "Unique name alias for CORD DIDs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
cord-utilities = { features = ["mock"], workspace = true }
sp-core = { features = ["std"], workspace = true }
sp-io = { features = ["std"], workspace = true }
sp-keystore = { features = ["std"], workspace = true }

[dependencies]
# External dependencies
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

# Internal dependencies
cord-utilities = { workspace = true }

# Substrate dependencies
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-core = { optional = true, workspace = true }

# Benchmarking dependencies
frame-benchmarking = { optional = true, workspace = true }
sp-io = { optional = true, workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"cord-utilities/runtime-benchmarks",
]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking?/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
	"cord-utilities/std",
	"sp-io?/std",
	"sp-keystore/std"
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"cord-utilities/try-runtime",
	"sp-runtime/try-runtime"
]
