[relaychain]
default_command = "./target/release/cord-loom"
default_args = ["-lparachain=debug"]
chain = "loom-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "charlie"
validator = true

[[relaychain.nodes]]
name = "dave"
validator = true

[[parachains]]
id = 1000
chain = "loom-asset-hub-local"
cumulus_based = true

# run alice as parachain collator
[[parachains.collators]]
name = "alice"
validator = true
command = "./target/release/weave"
args = ["-lparachain=debug"]

# run bob as parachain collator
[[parachains.collators]]
name = "bob"
validator = true
command = "./target/release/weave"
args = ["-lparachain=debug"]
ws_port = 9999

# [[parachains]]
# id = 1001
# chain = "cord-weave-coretime-dev"
# cumulus_based = true

# # run alice as parachain collator
# [[parachains.collators]]
# name = "alice"
# validator = true
# command = "./target/release/weave"
# args = ["-lparachain=debug, --force-authoring"]
