[package]
name = "pallet-network-score"
description = "Manage network scores"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dev-dependencies]
sp-core = { features = ["std"], workspace = true }
sp-keystore = { features = ["std"], workspace = true }
cord-utilities = { features = ["mock"], workspace = true }

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
cord-primitives = { workspace = true }
cord-utilities = { workspace = true }
pallet-chain-space = { workspace = true }
identifier = { workspace = true }

# Substrate dependencies
frame-benchmarking = { optional = true, workspace = true }
frame-system = { workspace = true }
frame-support = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-core = { optional = true, workspace = true }
sp-io = { optional = true, workspace = true }
sp-keystore = { optional = true, workspace = true }
pallet-timestamp = { workspace = true }


[features]
default = ['std']
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"cord-utilities/runtime-benchmarks",
]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking?/std",
	"cord-primitives/std",
	"cord-utilities/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"pallet-chain-space/std",
	"pallet-timestamp/std",
	"identifier/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"cord-utilities/try-runtime",
]
