[package]
name = 'cord-node'
version = '0.5.8'
authors = ['Dhiway <info@dhiway.com>']
build = 'build.rs'
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[[bin]]
name = 'cord'
path = "src/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1" }
serde = { version = "1.0.130", features = ["derive"] }
futures = "0.3.17"
hex-literal = "0.3.4"
log = "0.4.14"
rand = "0.7.2"
structopt = { version = "0.3.25", optional = true }

# Substrate Client
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1", default-features = false, optional = true }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

# Substrate Primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.15-1" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

# Substrate Pallets
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

# Substrate Other
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

# node-specific dependencies
cord-runtime = { package = "cord-runtime", path = "../runtime" }
cord-primitives = { package = "cord-primitives", path="../primitives"}
cord-rpc = { package = "cord-rpc", path = "../rpc" }
cord-executor = { package = "cord-executor", path = "../executor" }
pallet-nix = {  default-features = false, path = '../pallets/nix' }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1" }
cord-inspect = { package = "cord-inspect", optional = true, path = "../inspect" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cord-executor = { package = "cord-executor", path = "../executor",  features = [
	"wasmtime",
] }
sc-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1", features = [
	"wasmtime",
] }
sc-service = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1", features = [
	"wasmtime",
] }
sp-trie = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1", features = [
	"memory-tracker",
] }

[dev-dependencies]
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sc-service-test = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
futures = "0.3.16"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = "0.23"
serde_json = "1.0"
regex = "1"
platforms = "2.0"
async-std = { version = "1.10.0", features = ["attributes"] }
soketto = "0.4.2"
criterion = { version = "0.3.5", features = [ "async_tokio" ] }
tokio = { version = "1.13", features = ["macros", "time"] }
jsonrpsee-ws-client = "0.4.1"
wait-timeout = "0.2"
remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1" }

[build-dependencies]
structopt = { version = "0.3.25", optional = true }
cord-inspect = { package = "cord-inspect", optional = true, path = "../inspect" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1" }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate",optional = true, branch = "polkadot-v0.9.15-1"}
substrate-frame-cli = { git = "https://github.com/paritytech/substrate", optional = true, branch = "polkadot-v0.9.15-1"}
sc-cli = { git = "https://github.com/paritytech/substrate",optional = true, branch = "polkadot-v0.9.15-1"}
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15-1"}


[features]
default = [ "cli" ]
cli = [
	"cord-executor/wasmi-errno",
	"cord-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
runtime-benchmarks = [
  "cord-runtime/runtime-benchmarks",
  "frame-benchmarking-cli",
]
