[package]
name = 'cord-executor'
version = '0.7.10'
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate", branch = "master" }

[dependencies]
cord-runtime = { package = "cord-runtime", path = "../runtime" }
sc-executor = { git = "https://github.com/dhiway/substrate", branch = "master" }
frame-benchmarking = { git = "https://github.com/dhiway/substrate", branch = "master" }

[dev-dependencies]
criterion = "0.3.0"
frame-support = { git = "https://github.com/dhiway/substrate", branch = "master" }
frame-system = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-balances = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-grandpa = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-indices = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-session = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-timestamp = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-transaction-payment = { git = "https://github.com/dhiway/substrate", branch = "master" }
pallet-treasury = { git = "https://github.com/dhiway/substrate", branch = "master" }
sp-application-crypto = { git = "https://github.com/dhiway/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/dhiway/substrate", branch = "master" }
sp-externalities = { git = "https://github.com/dhiway/substrate", branch = "master" }
wat = "1.0"
futures = "0.3.21"

[features]
stress-test = []

