[package]
name = "cord-runtime-api-did"
description = "Runtime APIs for dealing with DIDs."
version = '0.8.0'
authors = ['Dhiway <info@dhiway.com>','BOTLabs GmbH']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }

# Internal dependencies
did = { package = "pallet-did", path="../../../pallets/did", default-features = false }

# Substrate 
sp-api = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.37", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate", branch = "release-v0.9.37", default-features = false }

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-api/std",
  "sp-std/std",
  "scale-info/std",
  "did/std",
]
