[package]
name = 'cord-authority-membership'
version = "0.9.0"
authors = ['Dhiway Networks <info@dhiway.com>']
edition = '2021'
license = "GPL-3.0"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.1.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = [
	"derive",
] }
serde = { version = "1.0.188", default-features = false, optional = true }
network-membership = { package = "network-membership", path = "../../primitives/network-membership", default-features = false }
pallet-network-membership = { package = "pallet-network-membership", path = "../../pallets/network-membership", default-features = false }
pallet-offences = { package = "pallet-offences", path = "../../pallets/offences", default-features = false }
log = { version = "0.4.17", default-features = false }

# Substrate dependencies
frame-system = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
frame-support = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
sp-runtime = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
sp-std = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
sp-core = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
sp-staking = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }
pallet-session = { git = "https://github.com/dhiway/substrate-sdk", features = [
	"historical",
], default-features = false, branch = "release-v1.1.0" }
sp-state-machine = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }


[dev-dependencies]
# serde = { version = "1.0.188", default-features = false }
sp-io = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.1.0" }

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'serde',
	'network-membership/std',
	'pallet-network-membership/std',
	'frame-system/std',
	'frame-support/std',
	'sp-runtime/std',
	'sp-std/std',
	'sp-core/std',
	'sp-staking/std',
	"sp-state-machine/std",
	'pallet-session/std',
	'pallet-offences/std',
	'log/std',
]
try-runtime = ['frame-support/try-runtime']
