name: dev PR submit

on:
  pull_request:
    branches:
      - dev-0.8.0
      - develop
    paths-ignore:
      - 'doc/**'
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    
    - name: Install necessary packages
      run: sudo apt-get install protobuf-compiler libssl-dev
    
    - name: Show active toolchain
      run: rustup show active-toolchain

    - name: Check
      run: cargo check

    - name: Test
      run: cargo test
    