name: pr-submit
on:
  pull_request:
    branches: [ develop]
    paths-ignore:
      - "doc/**"
      - "**.md"
defaults:
  run:
    shell: bash

jobs:
  develop-pr-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libssl-dev

      - name: Show active toolchain
        run: rustup show active-toolchain

      - name: Setup Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Check code syntax
        run: cargo check --release --all --all-targets --locked --verbose --color always

      - name: Run tests
        run: cargo test --release --all --all-targets --locked --features=runtime-benchmarks --no-fail-fast --verbose --color always
