# Buildx Platforms:
#
# `linux/amd64` - x86-64 Linux OS
# `linux/arm64` - 64-bit ARM architecture.
#

name: docker

on:
  push:
    branches:
      - develop
      - "release*"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_SERVER: docker.io
      DOCKER_USER: dhiway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Setup hardware emulator using QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        # Setup Docker Buildx for multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with Dockerhub using a Docker password secret
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_SERVER }}
          username: ${{ env.DOCKER_USER }}
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and Push Docker Image
        run: |
          # Get the branch name
          DOCKER_BRANCH=${{ github.ref }}
          DOCKER_BRANCH=${DOCKER_BRANCH/refs\/heads\//}

          # Build the Docker image with Buildx
          docker buildx build \
            --push \
            --no-cache \
            --file Dockerfile \
            --tag ${{ env.IMAGE_REPOSITORY }}:${DOCKER_BRANCH} \
            --tag ${{ env.DOCKER_SERVER }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_REPOSITORY }}:${DOCKER_BRANCH} \
            --tag ${{ env.DOCKER_SERVER }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_REPOSITORY }}:${IMAGE_TAG} \
            --platform linux/amd64,linux/arm64 \
            .
